// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MilkTeaWeb.Data;

#nullable disable

namespace MilkTeaWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260915061111_InitialPersistence")]
    partial class InitialPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.IceLevel", b =>
                {
                    b.Property<int>("IceLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IceLevelId"));

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.HasKey("IceLevelId");

                    b.HasIndex("Percentage")
                        .IsUnique();

                    b.ToTable("IceLevels", null, t =>
                        {
                            t.HasCheckConstraint("CK_IceLevel_DisplayOrder_NonNegative", "[DisplayOrder] >= 0");

                            t.HasCheckConstraint("CK_IceLevel_Percentage_Range", "[Percentage] BETWEEN 0 AND 100");
                        });

                    b.HasData(
                        new
                        {
                            IceLevelId = 1,
                            DisplayOrder = 0,
                            Percentage = 0
                        },
                        new
                        {
                            IceLevelId = 2,
                            DisplayOrder = 1,
                            Percentage = 30
                        },
                        new
                        {
                            IceLevelId = 3,
                            DisplayOrder = 2,
                            Percentage = 50
                        },
                        new
                        {
                            IceLevelId = 4,
                            DisplayOrder = 3,
                            Percentage = 70
                        },
                        new
                        {
                            IceLevelId = 5,
                            DisplayOrder = 4,
                            Percentage = 100
                        });
                });

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.ProductIceLevel", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("IceLevelId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "IceLevelId");

                    b.HasIndex("IceLevelId");

                    b.ToTable("ProductIceLevels", (string)null);
                });

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.ProductImage", b =>
                {
                    b.Property<int>("ProductImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductImageId"));

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ProductImageId");

                    b.HasIndex("ProductId", "DisplayOrder");

                    b.ToTable("ProductImages", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductImage_DisplayOrder_NonNegative", "[DisplayOrder] >= 0");
                        });
                });

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.ProductSize", b =>
                {
                    b.Property<int>("ProductSizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductSizeId"));

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.HasKey("ProductSizeId");

                    b.HasIndex("SizeId");

                    b.HasIndex("ProductId", "SizeId")
                        .IsUnique();

                    b.ToTable("ProductSizes", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductSize_Price_Positive", "[Price] > 0");
                        });
                });

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.ProductSugarLevel", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SugarLevelId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "SugarLevelId");

                    b.HasIndex("SugarLevelId");

                    b.ToTable("ProductSugarLevels", (string)null);
                });

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.ProductTopping", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ToppingId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "ToppingId");

                    b.HasIndex("ToppingId");

                    b.ToTable("ProductToppings", (string)null);
                });

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.Size", b =>
                {
                    b.Property<int>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeId"));

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SizeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sizes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Size_DisplayOrder_NonNegative", "[DisplayOrder] >= 0");
                        });
                });

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.Store", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StoreId");

                    b.ToTable("Stores", (string)null);
                });

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.SugarLevel", b =>
                {
                    b.Property<int>("SugarLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SugarLevelId"));

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.HasKey("SugarLevelId");

                    b.HasIndex("Percentage")
                        .IsUnique();

                    b.ToTable("SugarLevels", null, t =>
                        {
                            t.HasCheckConstraint("CK_SugarLevel_DisplayOrder_NonNegative", "[DisplayOrder] >= 0");

                            t.HasCheckConstraint("CK_SugarLevel_Percentage_Range", "[Percentage] BETWEEN 0 AND 100");
                        });

                    b.HasData(
                        new
                        {
                            SugarLevelId = 1,
                            DisplayOrder = 0,
                            Percentage = 0
                        },
                        new
                        {
                            SugarLevelId = 2,
                            DisplayOrder = 1,
                            Percentage = 30
                        },
                        new
                        {
                            SugarLevelId = 3,
                            DisplayOrder = 2,
                            Percentage = 50
                        },
                        new
                        {
                            SugarLevelId = 4,
                            DisplayOrder = 3,
                            Percentage = 70
                        },
                        new
                        {
                            SugarLevelId = 5,
                            DisplayOrder = 4,
                            Percentage = 100
                        });
                });

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.Topping", b =>
                {
                    b.Property<int>("ToppingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToppingId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ToppingId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Toppings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Topping_Price_NonNegative", "[Price] >= 0");
                        });
                });

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.Product", b =>
                {
                    b.HasOne("MilkTeaWeb.Models.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.ProductIceLevel", b =>
                {
                    b.HasOne("MilkTeaWeb.Models.Entities.IceLevel", "IceLevel")
                        .WithMany("ProductIceLevels")
                        .HasForeignKey("IceLevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MilkTeaWeb.Models.Entities.Product", "Product")
                        .WithMany("ProductIceLevels")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IceLevel");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.ProductImage", b =>
                {
                    b.HasOne("MilkTeaWeb.Models.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.ProductSize", b =>
                {
                    b.HasOne("MilkTeaWeb.Models.Entities.Product", "Product")
                        .WithMany("ProductSizes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MilkTeaWeb.Models.Entities.Size", "Size")
                        .WithMany("ProductSizes")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.ProductSugarLevel", b =>
                {
                    b.HasOne("MilkTeaWeb.Models.Entities.Product", "Product")
                        .WithMany("ProductSugarLevels")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MilkTeaWeb.Models.Entities.SugarLevel", "SugarLevel")
                        .WithMany("ProductSugarLevels")
                        .HasForeignKey("SugarLevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SugarLevel");
                });

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.ProductTopping", b =>
                {
                    b.HasOne("MilkTeaWeb.Models.Entities.Product", "Product")
                        .WithMany("ProductToppings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MilkTeaWeb.Models.Entities.Topping", "Topping")
                        .WithMany("ProductToppings")
                        .HasForeignKey("ToppingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.IceLevel", b =>
                {
                    b.Navigation("ProductIceLevels");
                });

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.Product", b =>
                {
                    b.Navigation("ProductIceLevels");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductSizes");

                    b.Navigation("ProductSugarLevels");

                    b.Navigation("ProductToppings");
                });

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.Size", b =>
                {
                    b.Navigation("ProductSizes");
                });

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.SugarLevel", b =>
                {
                    b.Navigation("ProductSugarLevels");
                });

            modelBuilder.Entity("MilkTeaWeb.Models.Entities.Topping", b =>
                {
                    b.Navigation("ProductToppings");
                });
#pragma warning restore 612, 618
        }
    }
}
